#!/bin/sh
remove_lv_home(){
    echo -en "You want remove VolGroup-lv_home(standart installed Centos6.0 from text mode)?[yN]:";read usespace
        if [ "$usespace" = "Y" -o "$usespace" = "y" ]; then
    	    sed -i 's/\/dev\/mapper\/VolGroup-lv_home/\#\/dev\/mapper\/VolGroup-lv_home/' /etc/fstab
	    [ -f /dev/mapper/VolGroup-lv_home ]&& umount /home && lvremove /dev/mapper/VolGroup-lv_home -ff
	fi
}
`[ "$1" == "-d" ] && echo $0|sed "s/\.\///"  #debug script`
